name: Main GitHub Action
on: [push]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ineshbose/portion-mate
          event-type: overleaf-push